import type { Person, Project, Task } from "./types";

export const people: Person[] = [
  {
    id: "user-alexander",
    name: "Александр Волков",
    initials: "АВ",
    position: "Генеральный директор",
    color: "#2d5be3",
    activeTasks: 7,
    overdueTasks: 0,
    completedMonth: 18,
    workload: 76,
  },
  {
    id: "user-maria",
    name: "Мария Соколова",
    initials: "МС",
    position: "Руководитель проектов",
    color: "#9b51e0",
    activeTasks: 9,
    overdueTasks: 2,
    completedMonth: 14,
    workload: 92,
  },
  {
    id: "user-ivan",
    name: "Иван Кузнецов",
    initials: "ИК",
    position: "Ведущий разработчик",
    color: "#0f9f82",
    activeTasks: 6,
    overdueTasks: 1,
    completedMonth: 21,
    workload: 81,
  },
  {
    id: "user-anna",
    name: "Анна Морозова",
    initials: "АМ",
    position: "Продуктовый дизайнер",
    color: "#e4663a",
    activeTasks: 8,
    overdueTasks: 1,
    completedMonth: 16,
    workload: 87,
  },
  {
    id: "user-dmitry",
    name: "Дмитрий Лебедев",
    initials: "ДЛ",
    position: "Маркетолог",
    color: "#cc8b14",
    activeTasks: 4,
    overdueTasks: 1,
    completedMonth: 12,
    workload: 63,
  },
  {
    id: "user-ekaterina",
    name: "Екатерина Новикова",
    initials: "ЕН",
    position: "Бизнес-аналитик",
    color: "#3276a8",
    activeTasks: 4,
    overdueTasks: 0,
    completedMonth: 15,
    workload: 58,
  },
];

const [alexander, maria, ivan, anna, dmitry, ekaterina] = people;

export const initialTasks: Task[] = [
  {
    id: "TSK-248",
    title: "Согласовать финальный дизайн главной страницы",
    project: "Редизайн корпоративного сайта",
    projectColor: "#315ae8",
    assignee: anna,
    status: "REVIEW",
    priority: "CRITICAL",
    state: "OVERDUE",
    progress: 92,
    startDate: "2026-08-12",
    dueDate: "2026-08-24",
    updatedAt: "20 мин назад",
    category: "Дизайн",
    comments: 8,
    hasDependency: true,
    description:
      "Подготовить финальную версию главной страницы с учётом комментариев руководства и передать макеты в разработку.",
    nextStep: "Получить подтверждение от Александра",
  },
  {
    id: "TSK-241",
    title: "Настроить синхронизацию с CRM",
    project: "Автоматизация отдела продаж",
    projectColor: "#8b5cf6",
    assignee: ivan,
    status: "BLOCKED",
    priority: "CRITICAL",
    state: "BLOCKED",
    progress: 38,
    startDate: "2026-08-15",
    dueDate: "2026-08-28",
    updatedAt: "1 ч назад",
    category: "Разработка",
    comments: 12,
    hasDependency: true,
    description:
      "Реализовать двустороннюю синхронизацию сделок и контактов с корпоративной CRM.",
    nextStep: "Получить ключ доступа от подрядчика",
  },
  {
    id: "TSK-253",
    title: "Подготовить материалы к запуску кампании",
    project: "Маркетинговая кампания",
    projectColor: "#ef8b2c",
    assignee: dmitry,
    status: "IN_PROGRESS",
    priority: "HIGH",
    state: "DUE_SOON",
    progress: 64,
    startDate: "2026-08-18",
    dueDate: "2026-08-26",
    updatedAt: "35 мин назад",
    category: "Маркетинг",
    comments: 5,
    description:
      "Собрать в единый комплект баннеры, тексты и медиаплан для осеннего запуска.",
    nextStep: "Проверить адаптацию баннеров",
  },
  {
    id: "TSK-229",
    title: "Провести нагрузочное тестирование API",
    project: "Запуск мобильного приложения",
    projectColor: "#0f9f82",
    assignee: ivan,
    status: "IN_PROGRESS",
    priority: "HIGH",
    state: "ATTENTION",
    progress: 41,
    startDate: "2026-08-11",
    dueDate: "2026-08-27",
    updatedAt: "2 ч назад",
    category: "Тестирование",
    comments: 4,
    description:
      "Проверить стабильность ключевых API-сценариев под ожидаемой пиковой нагрузкой.",
    nextStep: "Согласовать профиль нагрузки",
  },
  {
    id: "TSK-257",
    title: "Обновить коммерческое предложение",
    project: "Автоматизация отдела продаж",
    projectColor: "#8b5cf6",
    assignee: maria,
    status: "TODO",
    priority: "HIGH",
    state: "DUE_SOON",
    progress: 10,
    startDate: "2026-08-24",
    dueDate: "2026-08-26",
    updatedAt: "3 ч назад",
    category: "Продажи",
    comments: 2,
    description:
      "Актуализировать расчёт эффекта, сроки внедрения и состав работ в коммерческом предложении.",
    nextStep: "Получить новые тарифы",
  },
  {
    id: "TSK-235",
    title: "Собрать обратную связь от ключевых клиентов",
    project: "Клиентский портал",
    projectColor: "#de5c78",
    assignee: ekaterina,
    status: "IN_PROGRESS",
    priority: "MEDIUM",
    state: "OVERDUE",
    progress: 72,
    startDate: "2026-08-05",
    dueDate: "2026-08-22",
    updatedAt: "вчера",
    category: "Исследование",
    comments: 6,
    description:
      "Провести интервью и систематизировать обратную связь по новой версии кабинета.",
    nextStep: "Завершить два оставшихся интервью",
  },
  {
    id: "TSK-261",
    title: "Подготовить отчёт за август",
    project: "Внутренние процессы",
    projectColor: "#64748b",
    assignee: alexander,
    status: "TODO",
    priority: "MEDIUM",
    state: "ON_TRACK",
    progress: 15,
    startDate: "2026-08-24",
    dueDate: "2026-08-31",
    updatedAt: "4 ч назад",
    category: "Отчётность",
    comments: 1,
    description: "Собрать ключевые операционные показатели и выводы за август.",
    nextStep: "Запросить данные у руководителей",
  },
  {
    id: "TSK-218",
    title: "Разработать компоненты профиля пользователя",
    project: "Запуск мобильного приложения",
    projectColor: "#0f9f82",
    assignee: ivan,
    status: "REVIEW",
    priority: "MEDIUM",
    state: "ON_TRACK",
    progress: 88,
    startDate: "2026-08-08",
    dueDate: "2026-08-29",
    updatedAt: "5 ч назад",
    category: "Разработка",
    comments: 7,
    description: "Реализовать экран профиля и состояния редактирования данных.",
    nextStep: "Исправить замечания проверки кода",
  },
  {
    id: "TSK-264",
    title: "Сформировать карту пути клиента",
    project: "Клиентский портал",
    projectColor: "#de5c78",
    assignee: ekaterina,
    status: "TODO",
    priority: "LOW",
    state: "ON_TRACK",
    progress: 0,
    startDate: "2026-08-27",
    dueDate: "2026-09-05",
    updatedAt: "сегодня",
    category: "Исследование",
    comments: 0,
    description: "Описать основные пользовательские сценарии клиентского портала.",
    nextStep: "Собрать текущие исследования",
  },
  {
    id: "TSK-207",
    title: "Утвердить структуру нового каталога",
    project: "Редизайн корпоративного сайта",
    projectColor: "#315ae8",
    assignee: maria,
    status: "DONE",
    priority: "HIGH",
    state: "DONE",
    progress: 100,
    startDate: "2026-08-01",
    dueDate: "2026-08-18",
    updatedAt: "21 авг",
    category: "Контент",
    comments: 9,
    description: "Зафиксировать новую структуру услуг и посадочных страниц.",
    nextStep: "Завершено",
  },
  {
    id: "TSK-246",
    title: "Подготовить прототип раздела аналитики",
    project: "Клиентский портал",
    projectColor: "#de5c78",
    assignee: anna,
    status: "IN_PROGRESS",
    priority: "HIGH",
    state: "OVERDUE",
    progress: 58,
    startDate: "2026-08-10",
    dueDate: "2026-08-23",
    updatedAt: "6 ч назад",
    category: "Дизайн",
    comments: 11,
    description: "Подготовить кликабельный прототип аналитики для проверки гипотез.",
    nextStep: "Добавить состояние пустых данных",
  },
  {
    id: "TSK-268",
    title: "Настроить события продуктовой аналитики",
    project: "Запуск мобильного приложения",
    projectColor: "#0f9f82",
    assignee: ekaterina,
    status: "BACKLOG",
    priority: "LOW",
    state: "ON_TRACK",
    progress: 0,
    startDate: "2026-09-01",
    dueDate: null,
    updatedAt: "сегодня",
    category: "Аналитика",
    comments: 0,
    description: "Сформировать и внедрить карту событий для ключевых сценариев.",
    nextStep: "Утвердить перечень событий",
  },
];

export const projects: Project[] = [
  {
    id: "project-web",
    name: "Редизайн корпоративного сайта",
    description: "Новый визуальный язык и развитие ключевых страниц сайта",
    color: "#315ae8",
    owner: maria,
    members: [maria, anna, ivan, dmitry],
    progress: 78,
    tasks: 24,
    overdue: 2,
    dueDate: "2026-09-12",
    state: "ATTENTION",
  },
  {
    id: "project-mobile",
    name: "Запуск мобильного приложения",
    description: "Подготовка первой версии приложения к публичному запуску",
    color: "#0f9f82",
    owner: ivan,
    members: [ivan, anna, ekaterina],
    progress: 64,
    tasks: 31,
    overdue: 1,
    dueDate: "2026-09-30",
    state: "ON_TRACK",
  },
  {
    id: "project-sales",
    name: "Автоматизация отдела продаж",
    description: "Единый цифровой процесс от лида до закрытия сделки",
    color: "#8b5cf6",
    owner: maria,
    members: [maria, ivan, ekaterina],
    progress: 42,
    tasks: 18,
    overdue: 1,
    dueDate: "2026-10-15",
    state: "RISK",
  },
  {
    id: "project-marketing",
    name: "Маркетинговая кампания — осень",
    description: "Комплексный запуск новой продуктовой коммуникации",
    color: "#ef8b2c",
    owner: dmitry,
    members: [dmitry, anna, maria],
    progress: 56,
    tasks: 16,
    overdue: 1,
    dueDate: "2026-09-05",
    state: "ATTENTION",
  },
  {
    id: "project-portal",
    name: "Обновление клиентского портала",
    description: "Упрощение обслуживания и рост цифрового самообслуживания",
    color: "#de5c78",
    owner: ekaterina,
    members: [ekaterina, anna, ivan],
    progress: 35,
    tasks: 22,
    overdue: 2,
    dueDate: "2026-11-10",
    state: "ON_TRACK",
  },
];

export const activityItems = [
  {
    id: "activity-1",
    person: maria,
    text: "завершила задачу",
    target: "Подготовить план запуска",
    time: "12 минут назад",
    type: "done",
  },
  {
    id: "activity-2",
    person: anna,
    text: "добавила новый макет в задачу",
    target: "Согласовать финальный дизайн",
    time: "35 минут назад",
    type: "file",
  },
  {
    id: "activity-3",
    person: ivan,
    text: "перенёс задачу в статус «На проверке»",
    target: "Компоненты профиля пользователя",
    time: "1 час назад",
    type: "status",
  },
  {
    id: "activity-4",
    person: alexander,
    text: "изменил приоритет на «Критический»",
    target: "Настроить синхронизацию с CRM",
    time: "2 часа назад",
    type: "priority",
  },
  {
    id: "activity-5",
    person: ekaterina,
    text: "добавила комментарий к задаче",
    target: "Собрать обратную связь от клиентов",
    time: "3 часа назад",
    type: "comment",
  },
];

export const completionData = [
  { day: "19 авг", created: 5, completed: 3 },
  { day: "20 авг", created: 7, completed: 5 },
  { day: "21 авг", created: 4, completed: 6 },
  { day: "22 авг", created: 8, completed: 5 },
  { day: "23 авг", created: 3, completed: 4 },
  { day: "24 авг", created: 6, completed: 7 },
  { day: "25 авг", created: 5, completed: 8 },
];

export const priorityData = [
  { name: "Критические", value: 3, color: "#e5484d" },
  { name: "Высокие", value: 12, color: "#f59e0b" },
  { name: "Средние", value: 18, color: "#3b70ef" },
  { name: "Низкие", value: 9, color: "#94a3b8" },
];
